image: golang:1.23-alpine

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - go build

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  rules:
    - when: manual
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
