# fly.toml app configuration file generated for gobackend on 2024-11-03T09:05:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gobackend'
primary_region = 'sin'

[build]
  image = 'cecep31/gobackend:latest'

[env]
  DOMAIN = 'pilput.dev'
  ENABLE_LIMITER = 'true'
  S3_BUCKET = 'pilput-storage'
  S3_ENDPOINT = 's3.ap-southeast-1.amazonaws.com'
  S3_REGION = 'ap-southeast-1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_count = 2
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
